// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'defaultSize': string;
  'fullWidth': string;
  'green': string;
  'narrowSize': string;
  'root': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
