// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  error404: string;
  rocketTeam: string;
  root: string;
  whiteText: string;
  wording: string;
}
export const cssExports: CssExports;
export default cssExports;
